# Generated by Django 5.2.4 on 2025-07-10 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='课程名称'),
        ),
        migrations.AlterField(
            model_name='resourcefile',
            name='file',
            field=models.FileField(upload_to='%Y/%m/%d/', verbose_name='文件'),
        ),
        migrations.AlterField(
            model_name='resourcefile',
            name='title',
            field=models.CharField(max_length=50, verbose_name='资料标题'),
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='帖子标题')),
                ('content', models.TextField(verbose_name='帖子内容')),
                ('image', models.ImageField(blank=True, null=True, upload_to='post_images/%Y/%m/%d/', verbose_name='帖子图片')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='resources.course', verbose_name='所属课程')),
            ],
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='回复内容')),
                ('image', models.ImageField(blank=True, null=True, upload_to='reply_images/%Y/%m/%d/', verbose_name='回复图片')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='回复时间')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='resources.post', verbose_name='所属帖子')),
            ],
        ),
    ]
