# Generated by Django 5.1.3 on 2025-07-12 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0002_alter_course_name_alter_resourcefile_file_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="reply",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="child_replies",
                to="resources.reply",
            ),
        ),
    ]
